# Generated by Django 4.2.5 on 2023-09-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kelas',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nama',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
