# Generated by Django 4.2.5 on 2023-09-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_kelas_product_nama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
